jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run JavaScript script
        run: node script.js
        env:
          OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
